### ISSUE TITLE
keys parse not functioning

### ISSUE THREAD

**Issue by kw1knode** [White-Whale-Defi-Platform/migaloo-chain#100]
If you want to report a security issue, please follow our security policy: `https://github.com/White-Whale-Defi-Platform/migaloo-chain/blob/main/SECURITY.md`

---
## System details

Migaloo version: v1.0.0
OS & Version: Ubuntu 20.04.5 LTS / Ubuntu 5.13.0-52-generic
Commit hash: b4fbc788ece2878d2cfedb308a70f8d57e9407ea

---
## Steps to Reproduce

1. ```migalood keys parse migaloo1ajevnf3wa5y884ajnfk292mcqyth6qeetvl4y3```

**Expected results:**
```
bytes: F42D243BMYBYTES........

human: migaloo
```

**Actual results:**  Terminal hangs and force quit (ctrl+c) required.

---

**Comment by faddat** [comment]
hey kwik, did you ever get to a resolution here?

I wasn't able to reproduce it, but that doesn't mean it doesn't exist in your enviornment

**Comment by faddat** [comment]
Is anyone able to reporoduce this?
