### ISSUE TITLE
Migaloo v2

### ISSUE THREAD

**Issue by faddat** [White-Whale-Defi-Platform/migaloo-chain#112]
Migaloo v2 tracking issue

The key feature of v2 is alliance.  Any other features are nice-to-have at this stage.

Features:

- [ ] Alliance

Fixes:

- [ ] State sync

Nice-to-haves:

- [ ] async-icq
- [ ]  bump wasmd to v0.31.x-4611

**NOTE**

* cosmos-sdk v0.46.11 uses comet v0.34.27, and currently there's no version of skip for this.  I'm checking with the Skip team currently.

**Comment by Sen-Com** [comment]
Shall we squeeze in the updated token factory https://github.com/osmosis-labs/osmosis/pull/4417 @faddat?

**Comment by alanwilhelm** [comment]
Is notional wasmd the only one that works with sdk 46?

**Comment by faddat** [comment]
Yes.
