### ISSUE TITLE
Enable wasm Stargate queries

### ISSUE THREAD

**Issue by larry0x** [White-Whale-Defi-Platform/migaloo-chain#132]
## Improvement description

CosmWasm has a Stargate query feature that is disabled by default, due to the concern that some query responses may contain non-determinism. However, without this feature enabled, contracts are restricted to query methods provided by wasmvm bindings, which fail to include many custom modules such as tokenfactory.

To enable Stargate query, a whitelist must be provided when creating the WasmKeeper in app.go. For reference,

- Osmosis: https://github.com/osmosis-labs/osmosis/blob/main/wasmbinding/stargate_whitelist.go#L44

- Juno: https://github.com/CosmosContracts/juno/blob/e10e3241c9ec146670f1a08540104f017bed210c/app/keepers/keepers.go#L376-L395

I suggest Migaloo do the same, enabling the queries from bank, gov, staking, tokenfactory, ibc-transfer, and ICA modules.

**Comment by faddat** [comment]
Suggestion accepted

**Comment by faddat** [comment]
this should be closed by #141 -- it moves migaloo to the osmosis proto domain for token factory and enables stargate queries.
