### ISSUE TITLE
Test: blocked module account addresses

### ISSUE THREAD

**Issue by faddat** [White-Whale-Defi-Platform/migaloo-chain#23]
in app_test.go, we check to ensure that all module account addresses are blocked in bank.

After adding alliance, we need to ensure that gov and alliance are whitelisted.

**Comment by DongLieu** [comment]
Have you checked to see if the requirements are correct?

**Comment by DongLieu** [comment]
https://github.com/White-Whale-Defi-Platform/migaloo-chain/pull/30
