### ISSUE TITLE
Cosmos SDK upgrade to 0.47

### ISSUE THREAD

**Issue by kienn6034** [White-Whale-Defi-Platform/migaloo-chain#288]
# Proposal
Here is what we should do on `migaloo chain` repo.
- upgrade to `cosmos-sdk 47`

### Why?
Should apply the upgrade process of [terra core](https://github.com/terra-money/core/blob/release/v2.8/go.mod).

 `release/v2.4` -> `release/v2.8`

### What we get?
```
  +) Wasmd v0.45.0: use notional's fork with `token factory`
  +) comos-sdk v0.47.5
  +) ibc-go v7.3.-
  +) wasmvm v1.5.0
```

**Comment by hoank101** [comment]
https://github.com/White-Whale-Defi-Platform/migaloo-chain/pull/291
