### ISSUE TITLE
Set minimum Gas Price

### ISSUE THREAD

**Issue by Sen-Com** [White-Whale-Defi-Platform/migaloo-chain#42]
On init, app.toml should have a default gas price of 0uwhale

**Comment by pysel** [comment]
is this free to pick up?

**Comment by ThanhNhann** [comment]
Oh hey @pysel, Im working on this task in today afternoon, maybe you can pick another issue, sorry for don't set assign on this

**Comment by pysel** [comment]
gocha

**Comment by Sen-Com** [comment]
In #70
