### ISSUE TITLE
Remove `interchain-account-demo`

### ISSUE THREAD

**Issue by vuong177** [White-Whale-Defi-Platform/migaloo-chain#46]
## Description
InterTx (https://github.com/cosmos/interchain-accounts-demo) is not ready for use in the mainnet. We should remove it in `app.go`

---

**Comment by faddat** [comment]
hmmmm ok, basically that also means that we can remove the controller.

@Sen-Com ser, you good if we aren't an ica controller?  Do we need that for anything?

@vuong177 did I get that right?

**Comment by pysel** [comment]
hey guys, is it free to pick up?

**Comment by vuong177** [comment]
@faddat yep, we should remove the controller.

**Comment by vuong177** [comment]
@pysel yep, please make a PR for this
