### ISSUE TITLE
Adapt wrapped errors to sdk 46 style

### ISSUE THREAD

**Issue by faddat** [White-Whale-Defi-Platform/migaloo-chain#48]
in the PR

* #45

I

```go
//nolint:staticcheck // ignore SA1019 // TODO: migrate to cosmossdk.io/errors
```

to several wrapped errors.  @DongLieu can you please resolve this in a new PR?  #45 is good to go.

**Comment by DongLieu** [comment]
Ok. I will check all again and Adapt wrapped errors to sdk 46 style
